name: Build APK for Android 4.0.3

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build debug APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: dcards-debug-apk
        path: app/build/outputs/apk/debug/*.apk
