name: Android CI Build for Android 4.0.3

on:
  push:
    branches: [ "main", "master" ] # Запускати збірку при пуші в main або master
  pull_request:
    branches: [ "main", "master" ] # Запускати збірку при Pull Request

jobs:
  build:
    runs-on: ubuntu-latest # Використовуємо останню версію Ubuntu

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # Крок для завантаження коду з репозиторію

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '8' # Android 4.0.3 найкраще працює з Java 8
        distribution: 'temurin' # Рекомендований дистрибутив OpenJDK
        cache: gradle # Кешувати залежності Gradle для швидших збірок

    - name: Set up Android SDK # <<< ОНОВЛЕНИЙ КРОК
      uses: android/setup-sdk@v1
      with:
        sdk-platforms: 'android-15'
        build-tools-versions: '34.0.0' # Або інша версія build tools, яку ви використовуєте

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # Дозволити виконання Gradle Wrapper

    - name: Build Debug APK
      run: ./gradlew assembleDebug # Запуск збірки налагоджувальної версії APK

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk # Назва артефакту, який можна завантажити
        path: app/build/outputs/apk/debug/app-debug.apk # Шлях до згенерованого APK

    # Якщо вам потрібна релізна збірка, розкоментуйте та налаштуйте
    # - name: Build Release APK (Requires signing setup)
    #   run: ./gradlew assembleRelease
    # - name: Upload Release APK
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: app-release-apk
    #     path: app/build/outputs/apk/release/app-release-unsigned.apk # Або підписаний APK
