name: Build APK API14

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Verify Java version
      run: java -version

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        packages: |
          platform-tools
          "build-tools;19.0.3"
          "platforms;android-19"
        accept-android-sdk-licenses: true

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build debug APK
      run: ./gradlew clean assembleDebug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: Api14-apk
        path: app/build/outputs/apk/debug/app-debug.apk
