name: Build APK API14

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            platform-tools
            build-tools;19.0.3
            platforms;android-19
          accept-android-sdk-licenses: true

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew clean assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: Api14-apk
          path: app/build/outputs/apk/debug/app-debug.apk
